#
###################################
# Site wide configuration
####################################
#
title: Safely Typed
email: vinaleux@gmail.com
description:
url: https://vinalx.github.io
keywords: ["Programming"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /articles/:year/:month/:title
  insite:
    output: true
    permalink: /insite/:path
  nav:
    output: true
    permalink: /:path

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: VinaLx
  avatar: avatar.jpeg
  job: novice wizard
  bio: PL & music & game lover
  email: vinaleux@gmail.com
  disqus-shortname:
  twitter: Vinal_Eux
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: VinaLx
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
